(WIP) feat: creates MSR match logic
mapadoacolhimento/lambda-pedido-acolhimento pull request #12
Opened 2023-12-05 22:18 UTC by camilacrdoso

2023-12-06 21:17 UTC, camilacrdoso commented on src/process.ts
> +    const supportRequest = await bodySchema.validate(parsedBody);
Fiquei me perguntando se, antes de seguir com a lógica do match, deveríamos checar se o support_request está mesmo com o `status = open` como um double check pra evitar dar mais de um match para um mesmo support_request. 

A desvantagem é que isso custaria uma requisição para o banco.

2023-12-08 15:29 UTC, vivianedias reviewed
on point 🥇

2023-12-08 15:29 UTC, vivianedias commented on src/process.ts
> +    const supportRequest = await bodySchema.validate(parsedBody);
nao precisamos pq o status vai vir no payload, e a checagem de duplicados vai vir por la

2023-12-08 15:29 UTC, vivianedias commented on src/process.ts
> +          message: `Support request ${supportRequest.supportRequestId} received an Ideal Match with match_id: ${idealMatch.matchId}`,
nao faz sentido retornar o payload do match aq?

2023-12-08 15:29 UTC, vivianedias commented on src/utils/match/matchLogic.ts
> +    ) || null
🌟

2023-12-08 15:29 UTC, vivianedias commented on src/utils/match/matchLogic.ts
> +  const shouldReceiveAnOnlineMatch = randomNum % 2 === 0 ? true : false;
```suggestion
  const shouldReceiveAnOnlineMatch = randomNum % 2 === 0;
```

2023-12-08 15:29 UTC, vivianedias commented on src/utils/match/matchLogic.ts
> +  const closestVolunteers = fetchClosestVolunteers(
como nao fazemos reqs aq, eu mudaria o nome para algo como `findClosesVolunteers`

2023-12-15 18:22 UTC, vivianedias requested changes
otimos testes 💯

2023-12-15 18:22 UTC, vivianedias commented on src/utils/__tests__/match/matchLogic.spec.ts
> +  it("return null if msr city and state are not_found", () => {
```suggestion
  it("should return null if msr city and state are not_found", () => {
```

tem outros casos no arquivo tb

2023-12-15 18:22 UTC, vivianedias commented on src/utils/match/createMatch.ts
> +  const isVolunteerAvailable =
add testes para essa parte

2023-12-18 18:00 UTC, vivianedias approved these changes
arrasouuu 🤩

2023-12-19 20:03 UTC, merged