Feature/manual match
mapadoacolhimento/lambda-pedido-acolhimento pull request #29
Opened 2024-01-23 14:29 UTC by gloriateodoro

[ ] Criar handler e evento para o match manual no lambda
[ ] Buscar support request pelo id do ticket da msr
[ ] Buscar voluntária a partir do e-mail
[ ] Verificar disponibilidade de voluntária a partir do volunteer_id
[ ] Criar match entre voluntária e Msr

2024-01-23 15:01 UTC, vivianedias requested changes
lindo! mt feliz que conseguimos implementar uma logica nova reaproveitando codigo ✨

2024-01-23 15:56 UTC, camilacrdoso commented on src/manualMatch.ts
> +    const isVolunteerAvailable = checkVolunteerAvailability(
eu tô em dúvida se fazemos esse check porque lembro que as meninas de provisão de serviços disseram que às vezes elas querem fazer matches com voluntárias que já receberam o máximo de matches (porque elas conversam com essas voluntárias por whatsapp e as voluntárias pedem mais matches do que o máximo permitido)

vai zuar um pouco nosso dados D: mas acho que é melhor fazer o match mesmo que a voluntária não esteja disponível

2024-01-24 14:10 UTC, gloriateodoro commented on src/manualMatch.ts
> +    const isVolunteerAvailable = checkVolunteerAvailability(
@camilacrdoso @vivianedias fiz essa remoção, mas como estou aproveitando a função createMatch, é bom sabermos se nela tem alguma verificação que pode impedir esse tipo de match manual

2024-01-24 14:52 UTC, gloriateodoro commented on src/manualMatch.ts
> +      where: { zendeskTicketId: msrZendeskTicketId },
o msrZendeskTicketId é um number

2024-01-24 17:49 UTC, camilacrdoso commented on src/manualMatch.ts
> +    const isVolunteerAvailable = checkVolunteerAvailability(
A createMatch não faz esse tipo de block não! Então sem problemas

2024-01-25 14:00 UTC, vivianedias requested changes

2024-01-25 14:00 UTC, vivianedias commented on src/manualMatch.ts
> +        match,
```suggestion
        message: stringfyBigInt(match)
```

2024-01-25 14:00 UTC, vivianedias commented on src/manualMatch.ts
>      }
retornamos 3x esse erro 404, com mesma lógica. podemos extrair ela para uma função e reutilizar onde precisamos, seguindo o principio DRY.

isso já facilitaria a padronização dos nossos logs. sugiro que a gente logue não só a mensagem de erro, mas também onde ela foi feita e seu código. por exemplo:

```console.error(`[manual-match] - [404]: ${errorMessage}`);```

2024-01-25 14:00 UTC, vivianedias commented on src/manualMatch.ts
> +      console.error(errorMessage);
```suggestion
      console.error(`[match-manual] - [400]: ${errorMessage}`);
```

2024-01-25 14:00 UTC, vivianedias commented on src/manualMatch.ts
> +      console.error(errorMessage);
```suggestion
      console.error(`[match-manual] - [400]: ${errorMessage}`);
```

2024-01-25 14:00 UTC, vivianedias commented on src/manualMatch.ts
> +    const { msrZendeskTicketId, volunteerEmail } = (parsedBody || {}) as {
aquilo que comentei anteriormente sobre quando voce desestruturar um objeto dessa forma, ele vai retornar um erro, e nem vai chegar no if abaixo.

eu recomendo a gente usar o `yup` para validação... pra gente manter o padrao dos outros endpoints, e ele ja faz uma boa formatação de erro.

se formos seguir com ele, os checks abaixo não serao necessarios, e você vai ter que lidar com erro de validação no catch lá embaixo. assim como fazemos no `compose`.

2024-01-30 17:42 UTC, camilacrdoso approved these changes

2024-01-30 17:43 UTC, merged