[MAPA-380] Feat/add random busara ab experiment
mapadoacolhimento/lambda-pedido-acolhimento pull request #53
Opened 2024-06-05 20:08 UTC by dieh

2024-06-06 13:06 UTC, vivianedias requested changes
testes sempre aquecem o coraçaum <3

2024-06-06 13:06 UTC, vivianedias commented on src/emailClient/index.ts
> +  msrId: bigint,
bora transformar isso em um objeto para diminuir o numero de params

2024-06-06 13:06 UTC, vivianedias commented on src/emailClient/index.ts
> +  msrId: bigint,
msm coisa aq

2024-06-06 13:06 UTC, vivianedias commented on src/utils/saveBusaraABExperiment.ts
> +  hasMatch: boolean = false
nao conseguimos passar o matchId direto? buscar no banco assim pode dar ruim

2024-06-07 22:38 UTC, camilacrdoso approved these changes

2024-06-07 22:42 UTC, vivianedias approved these changes

2024-06-07 22:50 UTC, merged